services:
  traefik:
    image: traefik:v3.7
    command:
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      - "--api.insecure=true"
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    networks:
      - traefik-net

  db:
    image: "postgres:15.1"
    env_file:
      - ".env"
    environment:
      POSTGRES_USER: "${PG_USER}"
      POSTGRES_PASSWORD: "${PG_PASSWORD}"
      POSTGRES_DB: "${PG_DB}"
    volumes:
      - pg-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${PG_USER} -d ${PG_DB}"]
      interval: 30s
      timeout: 60s
      retries: 5
      start_period: 80s
    networks:
      - traefik-net

  migrate:
    build:
      context: .
      dockerfile: ./books-service/dockerfile
    command: ["sh", "-c", "sql-migrate up -config=dbconfig.yml -env=production"]
    env_file:
      - ".env"
    environment:
      DB_HOST: db
    depends_on:
      db:
        condition: service_healthy
    networks:
      - traefik-net
    restart: "no"

  books:
    build: 
      context: .
      dockerfile: ./books-service/dockerfile
    env_file:
      - ".env"
    networks:
      - traefik-net
    depends_on:
      migrate:
        condition: service_completed_successfully
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.books.rule=Host(`books.localhost`)"
      - "traefik.http.services.books.loadbalancer.server.port=8080"
      - "traefik.http.middlewares.books-rate-limit.ratelimit.average=5"
      - "traefik.http.middlewares.books-rate-limit.ratelimit.burst=10"
      - "traefik.http.middlewares.books-auth.forwardauth.address=http://auth-service:8080/api/v1/auth/verify"
      - "traefik.http.middlewares.books-auth.forwardauth.authResponseHeaders=X-User-Id"
      - "traefik.http.routers.books.middlewares=books-rate-limit@docker, books-auth@docker"

  auth-service:
    build:
      context: .
      dockerfile: ./books-auth/dockerfile
    env_file:
      - ".env"
    networks:
      - traefik-net
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.auth.rule=Host(`auth.localhost`) && (Path(`/api/v1/auth/login`) || Path(`/api/v1/auth/signup`))"
      - "traefik.http.services.auth.loadbalancer.server.port=8080"


networks:
  traefik-net:
    driver: bridge
volumes:
  pg-data:
